spring:
  datasource:
    url: jdbc:mysql://localhost:3306/author_book_rest
    username: root
    password: root

  liquibase:
    change-log: classpath*:db/change-log.xml

  jwt:
    secret: YXNkZmYkIyNzZFNEU0RBQVNERksjQEBkc2ZqZGZrZHNqQEAjZHNmZ2ZnZmdeXiYmWipeJSQkI2RzZHMkIyVzZDQ1MDk5KUkjJCg5V0ZTSUo=
    expiration: 600000

  upload:
     image:
      path: C:\Users\Grigorian_8\author-book-rest\images